# Generated by Django 5.0 on 2023-12-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, default=None, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=65, verbose_name='Nome completo')),
                ('profission', models.CharField(max_length=130, verbose_name='Curso de formação')),
                ('function_name', models.CharField(max_length=130, verbose_name='Área de atuação')),
                ('email', models.EmailField(max_length=60, verbose_name='E-Mail')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefone/Whatsapp')),
                ('locale', models.CharField(max_length=60, verbose_name='Localidade que reside')),
                ('content', models.TextField(verbose_name='Digite aqui seu conteúdo')),
                ('slug', models.SlugField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='URL')),
                ('is_published', models.BooleanField(default=False, help_text='Este campo precisará estar marcado para que apagina seja exibida publicamente.', verbose_name='Publicar?')),
            ],
            options={
                'verbose_name': 'Sobre min',
                'verbose_name_plural': 'Sobre min',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, default=None, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
    ]
