# Generated by Django 5.0 on 2023-12-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='assets/tecnology_image/%Y/%m', verbose_name='Adicionar imagem para a tecnologia'),
        ),
    ]
