# Generated by Django 5.0 on 2023-12-22 15:43

import django.db.models.deletion
import utils.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=65)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=600)),
                ('name_footer', models.CharField(max_length=65)),
                ('show_first_top_bar', models.BooleanField(default=True, verbose_name='Mostrar a primeira barrado Azul site.')),
                ('show_search', models.BooleanField(default=True, verbose_name='Mostrar campo de busca.')),
                ('show_dark_mode', models.BooleanField(default=True, verbose_name='Mostrar botão de modo escuro/branco.')),
                ('show_header', models.BooleanField(default=True, verbose_name='Mostrar cabeçalho do site.')),
                ('show_title_subtitle', models.BooleanField(default=True, verbose_name='Mostrar título e Subtitulo site.')),
                ('show_project_highlight', models.BooleanField(default=True, verbose_name='Mostrar Projeto em destaque.')),
                ('show_technology', models.BooleanField(default=True, verbose_name='Mostrar algumas tecnologias.')),
                ('show_some_projects', models.BooleanField(default=True, verbose_name='Mostrar Alguns projetos.')),
                ('show_menu', models.BooleanField(default=True, verbose_name='Mostrar menu do site.')),
                ('show_pagination', models.BooleanField(default=True, verbose_name='Mostrar paginação do site.')),
                ('show_footer', models.BooleanField(default=True, verbose_name='Mostrar rodapé do site.')),
                ('favicon', models.ImageField(blank=True, default='', upload_to='assets/favicon/%Y/%m', validators=[utils.model_validators.validate_png], verbose_name='Adicionar icone da janela/logotipo')),
            ],
            options={
                'verbose_name': 'Setup',
                'verbose_name_plural': 'Setups',
            },
        ),
        migrations.CreateModel(
            name='MenuLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('url_or_path', models.CharField(max_length=2048)),
                ('new_tab', models.BooleanField(default=False)),
                ('site_setup', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_setup.sitesetup')),
            ],
            options={
                'verbose_name': 'Menu Links',
            },
        ),
    ]
