# Generated by Django 5.0 on 2023-12-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='show_about_me',
            field=models.BooleanField(default=False, verbose_name='Mostrar página sobre mim'),
        ),
    ]
