# Generated by Django 5.0 on 2023-12-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='show_dark_mode',
            field=models.BooleanField(default=True),
        ),
    ]
