# Generated by Django 5.0 on 2023-12-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0002_sitesetup_show_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='show_about_me',
            field=models.BooleanField(default=True, verbose_name='Mostrar página sobre mim'),
        ),
    ]
