# Generated by Django 5.0 on 2023-12-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0002_sitesetup_show_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='show_first_top_bar',
            field=models.BooleanField(default=True),
        ),
    ]
