# Generated by Django 5.0.6 on 2025-04-23 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0003_alter_sitesetup_show_about_me'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuLink',
        ),
    ]
