# Generated by Django 5.0 on 2023-12-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0003_sitesetup_show_first_top_bar'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='show_title_description',
            field=models.BooleanField(default=True, verbose_name='Mostrar título da descrição'),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='show_description',
            field=models.BooleanField(default=True, verbose_name='Mostrar descrição'),
        ),
    ]
