# Generated by Django 5.0.6 on 2025-04-23 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_delete_menulink'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('url_or_path', models.CharField(max_length=2048)),
                ('new_tab', models.BooleanField(default=False)),
                ('site_setup', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_setup.sitesetup')),
            ],
            options={
                'verbose_name': 'Menu Links',
            },
        ),
    ]
