# Generated by Django 5.0 on 2023-12-22 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_sitesetup_faveicon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesetup',
            old_name='faveicon',
            new_name='favicon',
        ),
    ]
