# Generated by Django 5.0 on 2023-12-22 14:48

import utils.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_sitesetup_show_title_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetup',
            name='show_description',
        ),
        migrations.RemoveField(
            model_name='sitesetup',
            name='show_title_description',
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/favicon/%Y/%m', validators=[utils.model_validators.validate_png], verbose_name='Adicionar icone da janela/logotipo'),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='show_dark_mode',
            field=models.BooleanField(default=True, verbose_name='Mostrar botão de modo escuro/branco.'),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='show_first_top_bar',
            field=models.BooleanField(default=True, verbose_name='Mostrar a primeira barrado Azul site.'),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='show_footer',
            field=models.BooleanField(default=True, verbose_name='Mostrar rodapé do site.'),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='show_header',
            field=models.BooleanField(default=True, verbose_name='Mostrar cabeçalho do site.'),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='show_menu',
            field=models.BooleanField(default=True, verbose_name='Mostrar menu do site.'),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='show_pagination',
            field=models.BooleanField(default=True, verbose_name='Mostrar paginação do site.'),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='show_project_highlight',
            field=models.BooleanField(default=True, verbose_name='Mostrar Projeto em destaque.'),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='show_search',
            field=models.BooleanField(default=True, verbose_name='Mostrar campo de busca.'),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='show_some_projects',
            field=models.BooleanField(default=True, verbose_name='Mostrar Alguns projetos.'),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='show_technology',
            field=models.BooleanField(default=True, verbose_name='Mostrar algumas tecnologias.'),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='show_title_subtitle',
            field=models.BooleanField(default=True, verbose_name='Mostrar título e Subtitulo site.'),
        ),
    ]
