# Generated by Django 5.0.6 on 2025-04-23 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0005_menulink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuLink',
        ),
    ]
